version: '3.5'

services:       
  elastic:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
      restart: always
      environment:
        - ES_JAVA_OPTS=-Xms4g -Xmx4g
        - cluster.name=elastic
      ports:
        - 19202:9200
        - 19302:9300
      volumes:
        - elastic_data:/usr/share/elasticsearch/data
        - elastic_log:/usr/share/elasticsearch/logs

  kibana:
      image: docker.elastic.co/kibana/kibana:6.4.0
      restart: always
      ports:
      - 5602:5601
      environment:
        ELASTICSEARCH_URL: http://elastic:9200
      depends_on:
        - elastic

volumes:
  elastic_data: {}
  elastic_log: {}
  business_elastic_data: {}
  business_elastic_log: {}